### ISSUE TITLE
[Crash]: causing client to throw an exception and prevents launching

### ISSUE THREAD

**Issue by viktordimov** [Fuzss/puzzleslib#102]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.31-1.20.4-Fabric

### Other Mods Involved (Required)

Yes

### Notes (Required)

Client starts normally when removing puzzles-lib and all dependants.
No crash report generated, only a log.

### Crash Report (Required)

https://pastebin.com/TJU6YD8i

**Comment by viktordimov** [comment]
Tested with only puzzle's lib and its dependants on a separate instance. Works fine. Must be conflicting with other mods

**Comment by viktordimov** [comment]
Found responsible mod for the issue `ViaFabricPlus` - will report this to them as well.

**Comment by Fuzss** [comment]
Does v20.4.36 still give you this issue?

**Comment by viktordimov** [comment]
Yes. I just tested and got a crash.
[crash-2024-03-12_05.21.25-client.txt](https://github.com/Fuzss/puzzleslib/files/14567587/crash-2024-03-12_05.21.25-client.txt)

**Comment by Fuzss** [comment]
That's a different issue caused by ViaFabricPlus.
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector makeTextRed(I)Ljava/lang/String; in viafabricplus.mixins.json:fixes.minecraft.item.MixinDrawContext from mod viafabricplus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap viafabricplus-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 26 more
```

**Comment by viktordimov** [comment]
Puzzleslib gives no issues with any other mod on 1.20.4 
This is clearly a ViaFabricPlus issue.
