### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [Fuzss/puzzleslib#115]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

0.15.11

### Other Mods Involved (Required)

No

### Notes (Required)

[crash-2024-06-02_12.23.33-client.txt](https://github.com/user-attachments/files/15524175/crash-2024-06-02_12.23.33-client.txt)
1
[latest.log](https://github.com/user-attachments/files/15524176/latest.log)

### Crash Report (Required)

1

**Comment by Fuzss** [comment]
```
[12:23:26] [Render thread/ERROR]: Registry loading errors:
> Errors in registry minecraft:worldgen/placed_feature:
>> Errors in element corndelight:patch_wild_corn:
java.lang.IllegalStateException: Failed to parse corndelight:worldgen/placed_feature/patch_wild_corn.json from pack fabric
	at net.minecraft.class_7655.method_45122(class_7655.java:179)
	at net.minecraft.class_7655$class_7657.method_45132(class_7655.java:61)
	at net.minecraft.class_7655.method_45120(class_7655.java:98)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_7655.method_45121(class_7655.java:98)
	at net.minecraft.class_7237.method_45142(class_7237.java:67)
	at net.minecraft.class_7237.method_45143(class_7237.java:71)
	at net.minecraft.class_7237.method_42098(class_7237.java:34)
	at net.minecraft.class_525.method_31130(class_525.java:333)
	at net.minecraft.class_526.method_19944(class_526.java:60)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at imgui.glfw.ImGuiImplGlfw.mouseButtonCallback(ImGuiImplGlfw.java:123)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.handler$ilg000$fpsreducer$handleWaitEventsTimeout(RenderSystem.java:3008)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/placement_modifier_type]: farmersdelight:biome_is_overworld
	at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
	at net.minecraft.class_7655.method_45122(class_7655.java:176)
	... 33 more
`
``
