### ISSUE TITLE
[Bug]: target block tags not empty

### ISSUE THREAD

**Issue by Luke100000** [Fuzss/puzzleslib#130]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.1.21

### Other Mods Involved (Required)

Yes

### Notes (Required)

Adding the tag
```
{
  "replace": false,
  "values": [
    "minecraft:iron_bars",
    {
      "id": "#immersive_weathering:bars",
      "required": false
    },
    {
      "id": "diagonalwindows:minecraft/iron_bars",
      "required": false
    }
  ]
}

```

Causes
```
Caused by: java.lang.IllegalStateException: target block tags not empty
	at fuzs.puzzleslib.api.block.v1.BlockConversionHelper.copyBoundTags(BlockConversionHelper.java:77) ~[PuzzlesLib-v8.1.21-1.20.1-Fabric.jar:?]
	at java.util.Map.forEach(Unknown Source) ~[?:?]
	at fuzs.diagonalblocks.handler.DiagonalBlockHandler.copyBoundTags(DiagonalBlockHandler.java:81) ~[diagonalblocks-8.0.5-2a28cf26f12759c3.jar:?]
	at fuzs.diagonalblocks.handler.DiagonalBlockHandler.onTagsUpdated(DiagonalBlockHandler.java:42) ~[diagonalblocks-8.0.5-2a28cf26f12759c3.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.CommonLifecycleEvents.lambda$static$0(CommonLifecycleEvents.java:33) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-15099849194dcb7e.jar:?]
	at net.minecraft.class_5350.handler$zhj000$fabric-lifecycle-events-v1$hookRefresh(class_5350.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_5350.method_40421(class_5350.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_42097(class_7237.java:57) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_45694(class_7196.java:188) ~[client-intermediary.jar:?]
```

The tag should restore [compatibility](https://github.com/Luke100000/minecraft-comes-alive/issues/955) with MCA by adding diagonal bars to `#mca:iron_bars`. Am I doing something wrong here?

### latest.log (Required)

https://pastebin.com/3eT2P2Qn

**Comment by Fuzss** [comment]
Only add vanilla iron bars to the tag. All tags from that are copied over automatically to the diagonal variant.
