### ISSUE TITLE
[Crash]: Calling common config when it is not yet available!

### ISSUE THREAD

**Issue by DisdainofDeimos** [Fuzss/puzzleslib#142]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.1.24

### Other Mods Involved (Required)

Yes

### Notes (Required)

I have no idea why this is happening, may not be the cause of my crashes but worth mentioning to you nonetheless. Errors mention a few other mods including Botania, Not Enough Crashes, and Distinguished Potions. Sorry I can't provide more information, thanks for all the work you do for us <3

### Crash Report (Required)

https://mclo.gs/aDbvhDz

### latest.log (Optional)

https://mclo.gs/cjoAlEy

**Comment by tasxatzial** [comment]
Similar error here for 1.20.1 fabric. Easy magic mod in the log.

```
[19:20:42] [Render thread/ERROR]: Calling server config when it is not yet available! This is a bug! Message: Config data is missing
java.lang.Exception: Config not yet available
	at fuzs.puzzleslib.impl.config.ConfigDataHolderImpl.lambda$testAvailable$2(ConfigDataHolderImpl.java:88) ~[PuzzlesLib-v8.1.33-1.20.1-Fabric.jar:?]
	at com.mojang.datafixers.util.Either$Right.ifRight(Either.java:109) ~[datafixerupper-6.0.8.jar:?]
	at fuzs.puzzleslib.impl.config.ConfigDataHolderImpl.testAvailable(ConfigDataHolderImpl.java:87) ~[PuzzlesLib-v8.1.33-1.20.1-Fabric.jar:?]
	at fuzs.puzzleslib.impl.config.ConfigDataHolderImpl.getOrCreateDefaultConfig(ConfigDataHolderImpl.java:54) ~[PuzzlesLib-v8.1.33-1.20.1-Fabric.jar:?]
	at fuzs.puzzleslib.impl.config.ConfigDataHolderImpl.getConfig(ConfigDataHolderImpl.java:49) ~[PuzzlesLib-v8.1.33-1.20.1-Fabric.jar:?]
	at fuzs.puzzleslib.api.config.v3.ConfigHolder.get(ConfigHolder.java:42) ~[PuzzlesLib-v8.1.33-1.20.1-Fabric.jar:?]
	at fuzs.puzzleslib.impl.config.ConfigHolderRegistry.get(ConfigHolderRegistry.java:16) ~[PuzzlesLib-v8.1.33-1.20.1-Fabric.jar:?]
	at fuzs.easymagic.world.level.block.entity.ModEnchantmentTableBlockEntity.method_5439(ModEnchantmentTableBlockEntity.java:78) ~[EasyMagic-v8.0.1-1.20.1-Fabric.jar:?]
	at fuzs.easymagic.world.level.block.entity.ModEnchantmentTableBlockEntity.method_5438(ModEnchantmentTableBlockEntity.java:93) ~[EasyMagic-v8.0.1-1.20.1-Fabric.jar:?]
	at fuzs.easymagic.client.renderer.blockentity.ModEnchantTableRenderer.method_3571(ModEnchantTableRenderer.java:35) ~[EasyMagic-v8.0.1-1.20.1-Fabric.jar:?]
	at fuzs.easymagic.client.renderer.blockentity.ModEnchantTableRenderer.method_3569(ModEnchantTableRenderer.java:25) ~[EasyMagic-v8.0.1-1.20.1-Fabric.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3554(class_824.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:79) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:373) ~[sodium-fabric-0.5.13+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$epi000$iris$addToList(SodiumWorldRenderer.java:589) ~[sodium-fabric-0.5.13+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:312) ~[sodium-fabric-0.5.13+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:275) ~[sodium-fabric-0.5.13+mc1.20.1.jar:?]
	at net.minecraft.class_761.handler$ikd000$sodium$onRenderBlockEntities(class_761.java:25099) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1372) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.14.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```


Edit:I haven't got a crash though
