### ISSUE TITLE
[Crash]: Strange crash pointing to Puzzleslib after updating to v8.0.4-1.20.1

### ISSUE THREAD

**Issue by vico93** [Fuzss/puzzleslib#54]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.4

### Notes (Required)

Crash happened when opening an existing singleplayer world.

Crash report and latest.log in the attached gist.

### Crash Report (Required)

https://gist.github.com/vico93/90b301c779033837fcb06bd6dc8f3761

### latest.log (Optional)

https://gist.github.com/vico93/90b301c779033837fcb06bd6dc8f3761

**Comment by sternschnaube** [comment]
When I started my Minecraft, shortly after seeing the title menu, it closed with this crash report:

java.lang.NullPointerException: overrides is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at fuzs.puzzleslib.impl.client.init.FabricItemDisplayOverrides.getItemModelDisplayOverride(FabricItemDisplayOverrides.java:33)
	at net.minecraft.class_918.localvar$iob000$puzzleslib$render(class_918.java:5518)
	at net.minecraft.class_918.method_23179(class_918.java:122)
	at net.minecraft.class_332.method_51425(class_332.java:531)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51445(class_332.java:503)
	at com.github.scotsguy.nowplaying.NowPlayingToast.method_1986(NowPlayingToast.java:67)
	at net.minecraft.class_374$class_375.method_2002(class_374.java:153)
	at net.minecraft.class_374.method_45074(class_374.java:36)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at net.minecraft.class_374.method_1996(class_374.java:35)
	at net.minecraft.class_757.method_3192(class_757.java:972)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by palindali** [comment]
I'm getting the same exact issue!

**Comment by Jolihan566** [comment]
Same issue affecting me. Doesn't seem to be a problem on 8.0.2

**Comment by Fuzss** [comment]
Thanks a lot for reporting guys! Fixed in v8.0.5.
