### ISSUE TITLE
[Bug]: Unable to find Fabric biome modification field on Quilt

### ISSUE THREAD

**Issue by Steveplays28** [Fuzss/puzzleslib#75]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.24

### Notes (Required)

This error happens when loading a world on Quilt with Puzzles Lib and Ender Zoology (`v8.0.1`) installed.
Sorry for the massive log file, there's some BYG stuff I've been meaning to fix. Error is at the bottom if you view the full file.

Here's just the error in a dropdown so it's easier to get back to:

<details>
<summary>Error log</summary>

```log
[15:59:34] [Render thread/WARN] (Puzzles Lib) Unable to find field net.fabricmc.fabric.impl.biome.modification.BiomeModificationContextImpl$SpawnSettingsContextImpl.fabricSpawners
java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.biome.modification.BiomeModificationContextImpl$SpawnSettingsContextImpl
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:175) ~[quilt-loader-0.21.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.21.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.21.0-beta.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at fuzs.puzzleslib.api.core.v1.ReflectionHelper.findField(ReflectionHelper.java:71) ~[transformed-mod-puzzleslib.i0:0/:?]
	at fuzs.puzzleslib.impl.biome.MobSpawnSettingsContextFabric.findFabricSpawners(MobSpawnSettingsContextFabric.java:75) ~[transformed-mod-puzzleslib.i0:0/:?]
	at fuzs.puzzleslib.impl.biome.MobSpawnSettingsContextFabric.getSpawnerData(MobSpawnSettingsContextFabric.java:70) ~[transformed-mod-puzzleslib.i0:0/:?]
	at fuzs.enderzoology.EnderZoology.findVanillaSpawnData(EnderZoology.java:206) ~[transformed-mod-enderzoology.i0:0/:?]
	at fuzs.enderzoology.EnderZoology.registerSpawnData(EnderZoology.java:202) ~[transformed-mod-enderzoology.i0:0/:?]
	at fuzs.enderzoology.EnderZoology.lambda$onRegisterBiomeModifications$8(EnderZoology.java:170) ~[transformed-mod-enderzoology.i0:0/:?]
	at fuzs.puzzleslib.impl.core.context.BiomeModificationsContextFabricImpl.lambda$registerBiomeModification$1(BiomeModificationsContextFabricImpl.java:47) ~[transformed-mod-puzzleslib.i0:0/:?]
	at org.quiltmc.qsl.worldgen.biome.impl.modification.BiomeModificationImpl$ModifierRecord.apply(BiomeModificationImpl.java:295) ~[transformed-mod-quilt-biome.i0:0/:?]
	at org.quiltmc.qsl.worldgen.biome.impl.modification.BiomeModificationImpl.finalizeWorldGen(BiomeModificationImpl.java:214) ~[transformed-mod-quilt-biome.i0:0/:?]
	at net.minecraft.server.MinecraftServer.handler$jai001$quilt_biome$finalizeWorldGen(MinecraftServer.java:11842) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:304) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:50) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.MinecraftClient.method_29603(MinecraftClient.java:2094) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.startServer(MinecraftServer.java:272) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:2094) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.integrated.IntegratedServerLoader.method_43326(IntegratedServerLoader.java:235) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServerLoader.start(IntegratedServerLoader.java:233) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.integrated.IntegratedServerLoader.start(IntegratedServerLoader.java:64) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$WorldEntry.start(WorldListWidget.java:590) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$WorldEntry.play(WorldListWidget.java:480) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$WorldEntry.mouseClicked(WorldListWidget.java:402) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget.java:327) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:98) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:409) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:98) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:169) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:169) ~[transformed-mod-minecraft.i0:0/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1244) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.21.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.21.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.21.0-beta.4.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[15:59:34] [Render thread/INFO] (BiomeModificationImpl) Applied 4752 biome modifications to 310 of 310 new biomes in 119.9 ms
```

</details>

### latest.log (Optional)

https://gist.github.com/Steveplays28/d56d5f4abf7ea4f9174f34c2f46ca53c

**Comment by Fuzss** [comment]
Thanks for reporting! This is no serious issue, the implementation has a built-in fallback in case the Fabric field is not found which is the case here.
I will disable the error message on Quilt in the future. A proper fix would require dedicated Quilt support which I don't have time for.

**Comment by Steveplays28** [comment]
Alright, disabling the error message on Quilt would be appreciated!
Thanks for making awesome mods.

**Comment by Fuzss** [comment]
Thanks for using them! :D

**Comment by Fuzss** [comment]
Disabled the error message on Quilt in v8.1.0.

**Comment by Steveplays28** [comment]
Thanks!
