### ISSUE TITLE
[Crash]: Game crashes when launching. "java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'puzzleslib'"

### ISSUE THREAD

**Issue by apostrophepi** [Fuzss/puzzleslib#93]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.11

### Notes (Required)

1. Launch modpack via Modrinth.
2. Wait for game to open.
3. Game crashes with error.

Checked what the issue could have been through https://misode.github.io/report/ and it says there was an issue with not being able to execute the "main" entrypoint stage. Might not actually be a fault of Puzzles Lib, but I thought I'd try and check here just to be sure.

(Don't question why I'm playing with almost 400 mods, I enjoy the dangerous lifestyle.)

### Crash Report (Required)

https://gist.github.com/apostrophepi/c125cc6a0d4dd360ab89ee505a1da368

### latest.log (Optional)

https://gist.github.com/apostrophepi/3808d26a5e7dd9f963727bea23b99720

**Comment by Fuzss** [comment]
Caused by cookeymod:
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector renderWithOverlay(Lnet/minecraft/class_3887;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILnet/minecraft/class_1297;FFFFFF)V in cookeymod.mixins.json:client.LivingEntityRendererMixin from mod cookeymod failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap cookeymod-vanilla-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 50 more
```

**Comment by apostrophepi** [comment]
Odd. I've tried removing it and yet it still gives the error. Well thanks for the confirmation!

(I'm going to loathe going through which mod is the offender...)
